<<<<<<< HEAD
[2025-09-20 09:02:36,071] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 09:02:40,198] INFO django.server:213 — "GET /user/register/ HTTP/1.1" 200 6872
[2025-09-20 09:02:59,341] WARNING django.request:253 — Bad Request: /user/register/
[2025-09-20 09:02:59,342] WARNING django.server:213 — "POST /user/register/ HTTP/1.1" 400 6938
[2025-09-20 09:03:08,029] WARNING django.request:253 — Bad Request: /user/register/
[2025-09-20 09:03:08,030] WARNING django.server:213 — "POST /user/register/ HTTP/1.1" 400 6932
[2025-09-20 09:03:20,465] WARNING django.request:253 — Bad Request: /user/register/
[2025-09-20 09:03:20,466] WARNING django.server:213 — "POST /user/register/ HTTP/1.1" 400 6938
[2025-09-20 09:03:25,651] WARNING django.request:253 — Bad Request: /user/register/
[2025-09-20 09:03:25,652] WARNING django.server:213 — "POST /user/register/ HTTP/1.1" 400 7035
[2025-09-20 09:03:43,913] INFO django.server:213 — "GET /admin/ HTTP/1.1" 302 0
[2025-09-20 09:03:43,929] INFO django.server:213 — "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4173
[2025-09-20 09:03:48,790] INFO django.server:213 — "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2025-09-20 09:03:48,823] INFO django.server:213 — "GET /admin/ HTTP/1.1" 200 13035
[2025-09-20 09:03:51,426] INFO django.server:213 — "GET /admin/users/myuser/ HTTP/1.1" 200 14994
[2025-09-20 09:03:51,462] INFO django.server:213 — "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
[2025-09-20 09:03:51,481] INFO django.server:213 — "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[2025-09-20 09:03:51,483] INFO django.server:213 — "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[2025-09-20 09:03:51,488] INFO django.server:213 — "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[2025-09-20 09:03:51,489] INFO django.server:213 — "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[2025-09-20 09:03:51,492] INFO django.server:213 — "GET /static/admin/js/core.js HTTP/1.1" 304 0
[2025-09-20 09:03:51,492] INFO django.server:213 — "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[2025-09-20 09:03:51,494] INFO django.server:213 — "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[2025-09-20 09:03:51,496] INFO django.server:213 — "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[2025-09-20 09:03:51,497] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-20 09:03:51,505] INFO django.server:213 — "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
[2025-09-20 09:03:51,508] INFO django.server:213 — "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[2025-09-20 09:03:51,607] INFO django.server:213 — "GET /static/admin/js/filters.js HTTP/1.1" 200 978
[2025-09-20 09:03:51,630] INFO django.server:213 — "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[2025-09-20 09:04:21,501] WARNING django.request:253 — Not Found: /register
[2025-09-20 09:04:21,502] WARNING django.server:213 — "GET /register HTTP/1.1" 404 2964
[2025-09-20 09:04:23,856] INFO django.server:213 — "GET /user/register/ HTTP/1.1" 200 6904
[2025-09-20 09:04:25,202] WARNING django.request:253 — Not Found: /user/logot
[2025-09-20 09:04:25,203] WARNING django.server:213 — "GET /user/logot HTTP/1.1" 404 3811
[2025-09-20 09:04:27,215] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 6902
[2025-09-20 09:04:29,344] INFO django.server:213 — "POST /user/logout/ HTTP/1.1" 200 6854
[2025-09-20 09:04:41,050] INFO django.server:213 — "GET /user/register/ HTTP/1.1" 200 6872
[2025-09-20 09:05:02,372] INFO users.views:31 — user: Hi
[2025-09-20 09:05:02,376] INFO django.server:213 — "POST /user/register/ HTTP/1.1" 201 7122
[2025-09-20 09:05:06,807] WARNING django.request:253 — Not Found: /shop/
[2025-09-20 09:05:06,808] WARNING django.server:213 — "GET /shop/ HTTP/1.1" 404 3289
[2025-09-20 09:05:08,920] INFO django.server:213 — "GET /admin/ HTTP/1.1" 302 0
[2025-09-20 09:05:08,929] INFO django.server:213 — "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4173
[2025-09-20 09:05:15,803] INFO django.server:213 — "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2025-09-20 09:05:15,833] INFO django.server:213 — "GET /admin/ HTTP/1.1" 200 13035
[2025-09-20 09:05:17,632] INFO django.server:213 — "GET /admin/users/myuser/ HTTP/1.1" 200 15625
[2025-09-20 09:05:17,717] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-20 09:05:22,570] WARNING django.request:253 — Forbidden: /user/logout/
[2025-09-20 09:05:22,571] WARNING django.server:213 — "POST /user/logout/ HTTP/1.1" 403 5225
[2025-09-20 09:05:28,162] INFO django.server:213 — "GET /user/register/ HTTP/1.1" 200 6904
[2025-09-20 09:05:29,498] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 6902
[2025-09-20 09:05:31,046] INFO django.server:213 — "POST /user/logout/ HTTP/1.1" 200 6854
[2025-09-20 09:05:34,066] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 6873
[2025-09-20 09:05:37,658] INFO django.server:213 — "GET /user/login/ HTTP/1.1" 200 6829
[2025-09-20 09:05:48,411] INFO users.views:61 — user: Hi
[2025-09-20 09:05:48,415] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 7074
[2025-09-20 09:05:55,402] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 6873
[2025-09-20 09:06:56,295] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-20 09:06:57,313] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 09:06:59,450] INFO django.server:213 — "GET /user/login/ HTTP/1.1" 200 6829
[2025-09-20 09:07:08,721] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 7105
[2025-09-20 09:07:11,930] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 6873
[2025-09-20 09:07:16,892] INFO django.server:213 — "POST /user/logout/ HTTP/1.1" 200 6854
[2025-09-20 09:08:05,681] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-20 09:08:06,460] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 09:08:09,835] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 6873
[2025-09-20 09:08:10,950] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 6873
[2025-09-20 09:08:28,629] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-20 09:08:29,309] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 09:11:46,928] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-20 09:11:47,506] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 09:12:28,527] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-20 09:12:28,947] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 09:12:53,845] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-20 09:12:54,304] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 09:13:05,339] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-20 09:13:05,788] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 09:14:04,199] INFO django.server:213 — "GET /user/register/ HTTP/1.1" 200 6872
[2025-09-20 09:14:08,552] WARNING django.request:253 — Not Found: /user/logout/
[2025-09-20 09:14:08,553] WARNING django.server:213 — "GET /user/logout/ HTTP/1.1" 404 6861
[2025-09-20 09:14:10,102] WARNING django.request:253 — Not Found: /user/logout/
[2025-09-20 09:14:10,103] WARNING django.server:213 — "GET /user/logout/ HTTP/1.1" 404 6861
[2025-09-20 09:14:12,311] INFO django.server:213 — "GET /user/register/ HTTP/1.1" 200 6872
[2025-09-20 09:14:29,392] INFO django.server:213 — "POST /user/register/ HTTP/1.1" 201 7159
[2025-09-20 09:14:32,608] INFO django.server:213 — "GET /user/login/ HTTP/1.1" 200 6861
[2025-09-20 09:14:50,786] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 7111
[2025-09-20 09:14:53,428] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 6902
[2025-09-20 09:15:50,696] INFO django.server:213 — "POST /user/logout/ HTTP/1.1" 200 6854
[2025-09-20 09:15:53,465] INFO django.server:213 — "GET /admin/ HTTP/1.1" 302 0
[2025-09-20 09:15:53,484] INFO django.server:213 — "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4173
[2025-09-20 09:15:55,115] WARNING django.request:253 — Not Found: /user/logout/
[2025-09-20 09:15:55,116] WARNING django.server:213 — "GET /user/logout/ HTTP/1.1" 404 6861
[2025-09-20 09:15:57,830] INFO django.server:213 — "GET /user/login/ HTTP/1.1" 200 6829
[2025-09-20 09:16:07,508] WARNING django.request:253 — Bad Request: /user/login/
[2025-09-20 09:16:07,509] WARNING django.server:213 — "POST /user/login/ HTTP/1.1" 400 6893
[2025-09-20 09:16:21,613] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 7085
[2025-09-20 09:16:25,706] INFO django.server:213 — "GET /admin/ HTTP/1.1" 302 0
[2025-09-20 09:16:25,716] INFO django.server:213 — "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4173
[2025-09-20 09:16:31,715] WARNING django.request:253 — Not Found: /user/logout/
[2025-09-20 09:16:31,716] WARNING django.server:213 — "GET /user/logout/ HTTP/1.1" 404 6861
[2025-09-20 09:16:32,065] WARNING django.request:253 — Not Found: /user/logout/
[2025-09-20 09:16:32,066] WARNING django.server:213 — "GET /user/logout/ HTTP/1.1" 404 6861
[2025-09-20 09:16:35,360] INFO django.server:213 — "GET /user/login/ HTTP/1.1" 200 6829
[2025-09-20 09:16:46,523] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 7085
[2025-09-20 09:16:58,039] WARNING django.request:253 — Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-20 09:16:58,040] WARNING django.server:213 — "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3084
[2025-09-20 09:17:00,828] INFO django.server:213 — "GET /user/login/ HTTP/1.1" 200 6829
[2025-09-20 09:17:01,553] WARNING django.request:253 — Not Found: /user/logout/
[2025-09-20 09:17:01,554] WARNING django.server:213 — "GET /user/logout/ HTTP/1.1" 404 6861
[2025-09-20 09:17:02,368] WARNING django.request:253 — Not Found: /user/logout/
[2025-09-20 09:17:02,369] WARNING django.server:213 — "GET /user/logout/ HTTP/1.1" 404 6861
[2025-09-20 09:17:07,068] INFO django.server:213 — "GET /admin/ HTTP/1.1" 302 0
[2025-09-20 09:17:07,080] INFO django.server:213 — "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4173
[2025-09-20 09:17:46,142] INFO django.server:213 — "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2025-09-20 09:17:46,178] INFO django.server:213 — "GET /admin/ HTTP/1.1" 200 13035
[2025-09-20 09:18:23,620] INFO django.server:213 — "GET /admin/users/myuser/ HTTP/1.1" 200 16261
[2025-09-20 09:18:23,703] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-20 09:19:08,316] INFO django.utils.autoreload:265 — /app/backend/settings.py changed, reloading.
[2025-09-20 09:19:09,168] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 09:19:31,095] INFO django.utils.autoreload:265 — /app/backend/settings.py changed, reloading.
[2025-09-20 09:19:31,567] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 09:19:42,073] INFO django.utils.autoreload:265 — /app/backend/settings.py changed, reloading.
[2025-09-20 09:19:42,543] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 09:19:56,897] INFO django.utils.autoreload:265 — /app/backend/settings.py changed, reloading.
[2025-09-20 09:19:57,317] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 09:22:20,590] INFO django.utils.autoreload:265 — /app/backend/settings.py changed, reloading.
[2025-09-20 09:22:21,683] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
=======
[2025-09-19 15:25:31,518] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-19 15:25:32,400] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 15:25:35,871] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-19 15:25:36,410] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 15:30:25,437] INFO django.utils.autoreload:265 — /app/shop/views.py changed, reloading.
[2025-09-19 15:30:26,168] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 15:30:32,928] INFO django.server:213 — "GET / HTTP/1.1" 200 6465
[2025-09-19 15:30:54,824] WARNING django.request:253 — Not Found: /cart/add/1
[2025-09-19 15:30:54,825] WARNING django.server:213 — "GET /cart/add/1 HTTP/1.1" 404 4728
[2025-09-19 15:31:01,980] ERROR django.request:253 — Internal Server Error: /cart/api/add/1/
[2025-09-19 15:31:01,981] ERROR django.server:213 — "GET /cart/api/add/1/ HTTP/1.1" 500 7184
[2025-09-19 15:31:43,409] INFO django.server:213 — "OPTIONS /cart/api/add/1/ HTTP/1.1" 200 7353
[2025-09-19 15:31:44,179] INFO django.server:213 — "OPTIONS /cart/api/add/1/ HTTP/1.1" 200 7353
[2025-09-19 15:31:45,454] ERROR django.request:253 — Internal Server Error: /cart/api/add/1/
[2025-09-19 15:31:45,455] ERROR django.server:213 — "GET /cart/api/add/1/ HTTP/1.1" 500 7184
[2025-09-19 15:36:02,530] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 15:36:16,166] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-19 15:36:16,194] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 15:36:20,265] ERROR django.request:253 — Internal Server Error: /cart/api/add/1/
[2025-09-19 15:36:20,267] ERROR django.server:213 — "POST /cart/api/add/1/ HTTP/1.1" 500 102
[2025-09-19 15:36:38,513] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 15:36:41,192] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-19 15:36:41,228] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 15:36:45,694] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5314
[2025-09-19 15:36:48,978] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 5320
[2025-09-19 15:37:13,972] ERROR django.request:253 — Internal Server Error: /cart/api/add/1/
[2025-09-19 15:37:13,973] ERROR django.server:213 — "GET /cart/api/add/1/?format=api HTTP/1.1" 500 7261
[2025-09-19 15:37:16,048] ERROR django.request:253 — Internal Server Error: /cart/api/add/1/
[2025-09-19 15:37:16,050] ERROR django.server:213 — "GET /cart/api/add/1/?format=api HTTP/1.1" 500 7261
[2025-09-19 15:37:20,693] ERROR django.request:253 — Internal Server Error: /cart/api/add/1/
[2025-09-19 15:37:20,695] ERROR django.server:213 — "GET /cart/api/add/1/?format=api HTTP/1.1" 500 7261
[2025-09-19 15:37:59,396] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-19 15:37:59,437] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 15:38:04,983] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-19 15:38:05,005] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 15:40:26,209] WARNING django.request:253 — Not Found: /shop/products/
[2025-09-19 15:40:26,211] WARNING django.server:213 — "GET /shop/products/ HTTP/1.1" 404 3308
[2025-09-19 15:40:28,555] WARNING django.request:253 — Not Found: /shop/products/
[2025-09-19 15:40:28,557] WARNING django.server:213 — "GET /shop/products/ HTTP/1.1" 404 3308
[2025-09-19 15:40:31,425] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-19 15:40:31,448] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 15:40:38,162] WARNING django.request:253 — Not Found: /shop/products/
[2025-09-19 15:40:38,163] WARNING django.server:213 — "GET /shop/products/ HTTP/1.1" 404 3308
[2025-09-19 15:40:43,106] WARNING django.request:253 — Not Found: /shop/products/
[2025-09-19 15:40:43,108] WARNING django.server:213 — "GET /shop/products/ HTTP/1.1" 404 3308
[2025-09-19 15:41:10,404] WARNING django.request:253 — Not Found: /shop/products/
[2025-09-19 15:41:10,405] WARNING django.server:213 — "GET /shop/products/ HTTP/1.1" 404 3308
[2025-09-19 15:41:15,623] WARNING django.request:253 — Not Found: /shop/product/
[2025-09-19 15:41:15,624] WARNING django.server:213 — "GET /shop/product/ HTTP/1.1" 404 3305
[2025-09-19 15:41:46,482] WARNING django.request:253 — Not Found: /shop/products/1
[2025-09-19 15:41:46,484] WARNING django.server:213 — "GET /shop/products/1 HTTP/1.1" 404 3311
[2025-09-19 15:41:58,578] INFO django.server:213 — "GET /products/1 HTTP/1.1" 301 0
[2025-09-19 15:41:58,617] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 6464
[2025-09-19 15:42:01,901] WARNING django.request:253 — Not Found: /products/
[2025-09-19 15:42:01,905] WARNING django.server:213 — "GET /products/ HTTP/1.1" 404 3705
[2025-09-19 15:42:05,106] WARNING django.request:253 — Not Found: /product/
[2025-09-19 15:42:05,107] WARNING django.server:213 — "GET /product/ HTTP/1.1" 404 3290
[2025-09-19 15:43:47,607] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-19 15:43:49,199] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 15:44:31,534] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-19 15:44:32,652] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 15:45:04,806] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-19 15:45:05,850] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 15:45:23,892] INFO django.utils.autoreload:265 — /app/products/serializers.py changed, reloading.
[2025-09-19 15:45:24,799] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 15:45:57,978] INFO django.utils.autoreload:265 — /app/products/serializers.py changed, reloading.
[2025-09-19 15:45:58,761] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 15:46:24,172] INFO django.utils.autoreload:265 — /app/products/urls.py changed, reloading.
[2025-09-19 15:46:25,025] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 15:46:52,924] INFO django.utils.autoreload:265 — /app/products/views.py changed, reloading.
[2025-09-19 15:46:53,698] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 15:47:25,963] INFO django.utils.autoreload:265 — /app/products/urls.py changed, reloading.
[2025-09-19 15:47:26,780] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 15:47:28,032] WARNING django.request:253 — Not Found: /product/api
[2025-09-19 15:47:28,033] WARNING django.server:213 — "GET /product/api HTTP/1.1" 404 3299
[2025-09-19 15:47:42,679] INFO django.server:213 — "GET /products/api HTTP/1.1" 301 0
[2025-09-19 15:47:42,770] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 7004
[2025-09-19 15:49:02,996] WARNING django.request:253 — Not Found: /shop/products/
[2025-09-19 15:49:03,003] WARNING django.server:213 — "GET /shop/products/ HTTP/1.1" 404 3308
[2025-09-19 15:50:34,827] INFO django.utils.autoreload:265 — /app/shop/urls.py changed, reloading.
[2025-09-19 15:50:36,146] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 15:50:49,474] INFO django.utils.autoreload:265 — /app/shop/urls.py changed, reloading.
[2025-09-19 15:50:50,295] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 15:51:00,586] WARNING django.request:253 — Not Found: /shop/products/
[2025-09-19 15:51:00,587] WARNING django.server:213 — "GET /shop/products/ HTTP/1.1" 404 3308
[2025-09-19 15:51:03,046] WARNING django.request:253 — Not Found: /shop
[2025-09-19 15:51:03,047] WARNING django.server:213 — "GET /shop HTTP/1.1" 404 3278
[2025-09-19 15:51:09,121] WARNING django.request:253 — Not Found: /shop
[2025-09-19 15:51:09,122] WARNING django.server:213 — "GET /shop HTTP/1.1" 404 3278
[2025-09-19 15:51:25,057] INFO django.utils.autoreload:265 — /app/backend/urls.py changed, reloading.
[2025-09-19 15:51:25,867] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 15:51:26,932] INFO django.server:213 — "GET /shop HTTP/1.1" 200 6783
[2025-09-19 15:53:43,592] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 15:54:23,426] INFO django.server:213 — "GET /shop HTTP/1.1" 200 6783
[2025-09-19 15:59:37,913] WARNING django.request:253 — Not Found: /shop/products/
[2025-09-19 15:59:37,914] WARNING django.server:213 — "GET /shop/products/ HTTP/1.1" 404 3316
[2025-09-19 16:00:14,824] WARNING django.request:253 — Not Found: /shop/products/
[2025-09-19 16:00:14,825] WARNING django.server:213 — "GET /shop/products/ HTTP/1.1" 404 3316
[2025-09-19 16:00:28,096] INFO django.server:213 — "GET /shop HTTP/1.1" 200 982
[2025-09-19 16:00:29,231] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-19 16:00:29,251] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 16:00:31,971] INFO django.server:213 — "GET /shop HTTP/1.1" 200 982
[2025-09-19 16:00:58,700] INFO django.server:213 — "GET /shop HTTP/1.1" 200 982
[2025-09-19 16:01:02,389] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-19 16:01:02,406] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 16:01:05,719] ERROR django.request:253 — Internal Server Error: /cart/api/add/1/
[2025-09-19 16:01:05,719] ERROR django.server:213 — "POST /cart/api/add/1/ HTTP/1.1" 500 102
[2025-09-19 16:01:28,346] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-19 16:01:28,366] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 16:01:29,842] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-19 16:01:29,864] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 16:01:33,716] INFO django.server:213 — "GET /shop HTTP/1.1" 200 982
[2025-09-19 16:01:38,462] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-19 16:01:38,482] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 16:02:37,386] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-19 16:02:37,404] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 16:02:39,659] INFO django.server:213 — "GET /products/api HTTP/1.1" 301 0
[2025-09-19 16:02:39,687] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 16:02:43,943] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-19 16:02:43,960] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 16:03:25,727] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 16:03:28,882] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-19 16:03:28,899] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 16:04:02,409] INFO django.server:213 — "GET /admin HTTP/1.1" 301 0
[2025-09-19 16:04:02,432] INFO django.server:213 — "GET /admin/ HTTP/1.1" 302 0
[2025-09-19 16:04:02,477] INFO django.server:213 — "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4173
[2025-09-19 16:04:02,562] INFO django.server:213 — "GET /static/admin/css/login.css HTTP/1.1" 200 951
[2025-09-19 16:04:06,332] INFO django.server:213 — "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2025-09-19 16:04:07,013] INFO django.server:213 — "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2025-09-19 16:04:07,066] INFO django.server:213 — "GET /admin/ HTTP/1.1" 200 12181
[2025-09-19 16:04:07,101] INFO django.server:213 — "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
[2025-09-19 16:04:14,214] INFO django.server:213 — "GET /admin/auth/group/ HTTP/1.1" 200 11309
[2025-09-19 16:04:14,278] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-19 16:04:15,887] INFO django.server:213 — "GET /admin/cart/cartitem/ HTTP/1.1" 200 10982
[2025-09-19 16:04:15,932] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-19 16:04:16,655] INFO django.server:213 — "GET /admin/cart/carts/ HTTP/1.1" 200 10956
[2025-09-19 16:04:16,712] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-19 16:04:17,702] INFO django.server:213 — "GET /admin/products/category/ HTTP/1.1" 200 12879
[2025-09-19 16:04:17,746] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-19 16:04:17,770] INFO django.server:213 — "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[2025-09-19 16:04:20,848] INFO django.server:213 — "GET /admin/products/product/ HTTP/1.1" 200 16238
[2025-09-19 16:04:20,883] INFO django.server:213 — "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
[2025-09-19 16:04:20,900] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-19 16:04:21,418] INFO django.server:213 — "GET /admin/products/subcategory/ HTTP/1.1" 200 13116
[2025-09-19 16:04:21,470] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-19 16:04:21,996] INFO django.server:213 — "GET /admin/wishlist/wishlist/ HTTP/1.1" 200 10993
[2025-09-19 16:04:22,049] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-19 16:04:27,061] INFO django.server:213 — "GET /admin/wishlist/wishlist/ HTTP/1.1" 200 10993
[2025-09-19 16:04:27,118] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-19 16:04:30,468] INFO django.server:213 — "GET /admin/ HTTP/1.1" 200 12181
[2025-09-19 16:04:38,548] INFO django.server:213 — "GET /admin/cart/cartitem/ HTTP/1.1" 200 10982
[2025-09-19 16:04:38,614] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-19 16:04:41,007] INFO django.server:213 — "GET /admin/cart/cartitem/add/ HTTP/1.1" 200 15859
[2025-09-19 16:04:41,060] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-19 16:04:46,809] INFO django.server:213 — "GET /admin/cart/carts/ HTTP/1.1" 200 10956
[2025-09-19 16:04:46,866] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-19 16:04:48,193] INFO django.server:213 — "GET /admin/cart/carts/add/ HTTP/1.1" 200 11904
[2025-09-19 16:04:48,248] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-19 16:05:07,542] INFO django.server:213 — "GET /admin/ HTTP/1.1" 200 12181
[2025-09-19 16:06:01,493] INFO django.server:213 — "OPTIONS /user/register/ HTTP/1.1" 200 0
[2025-09-19 16:06:01,579] ERROR django.request:253 — Internal Server Error: /user/register/
[2025-09-19 16:06:01,580] ERROR django.server:213 — "POST /user/register/ HTTP/1.1" 500 105
[2025-09-19 16:06:13,391] INFO django.server:213 — "GET /admin/ HTTP/1.1" 200 12181
[2025-09-19 16:07:20,328] INFO django.utils.autoreload:265 — /app/users/admin.py changed, reloading.
[2025-09-19 16:07:21,226] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 16:07:48,604] INFO django.utils.autoreload:265 — /app/users/admin.py changed, reloading.
[2025-09-19 16:07:49,410] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 16:08:52,515] INFO django.utils.autoreload:265 — /app/users/admin.py changed, reloading.
[2025-09-19 16:08:53,822] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 16:09:04,238] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 16:10:34,426] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 16:10:36,477] INFO django.server:213 — "GET /admin/ HTTP/1.1" 200 12181
[2025-09-19 16:10:41,697] INFO django.server:213 — "GET /admin/ HTTP/1.1" 200 12181
[2025-09-19 16:10:41,712] INFO django.utils.autoreload:265 — /app/users/admin.py changed, reloading.
[2025-09-19 16:10:42,611] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 16:10:43,718] INFO django.server:213 — "GET /admin/ HTTP/1.1" 200 13218
[2025-09-19 16:10:48,135] INFO django.server:213 — "GET /admin/users/myuser/ HTTP/1.1" 200 14344
[2025-09-19 16:10:48,215] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-19 16:10:54,349] INFO django.server:213 — "GET /admin/users/myuser/1/change/ HTTP/1.1" 200 27741
[2025-09-19 16:10:54,408] INFO django.server:213 — "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
[2025-09-19 16:10:54,412] INFO django.server:213 — "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
[2025-09-19 16:10:54,426] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-19 16:10:54,493] INFO django.server:213 — "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[2025-09-19 16:10:54,493] INFO django.server:213 — "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[2025-09-19 16:11:00,697] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 37
[2025-09-19 16:11:00,707] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 16:11:35,476] INFO django.server:213 — "GET //user/api/check-auth/ HTTP/1.1" 200 5294
[2025-09-19 16:11:46,558] WARNING django.request:253 — Not Found: /user/api/logut/
[2025-09-19 16:11:46,559] WARNING django.server:213 — "GET /user/api/logut/ HTTP/1.1" 404 3826
[2025-09-19 16:11:59,204] WARNING django.request:253 — Not Found: /user/api/logout/
[2025-09-19 16:11:59,206] WARNING django.server:213 — "GET /user/api/logout/ HTTP/1.1" 404 3829
[2025-09-19 16:12:06,951] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 5227
[2025-09-19 16:12:11,683] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 5230
[2025-09-19 16:12:13,958] INFO django.server:213 — "GET /admin/users/myuser/1/change/ HTTP/1.1" 302 0
[2025-09-19 16:12:13,978] INFO django.server:213 — "GET /admin/login/?next=/admin/users/myuser/1/change/ HTTP/1.1" 200 4217
[2025-09-19 16:12:27,785] INFO django.server:213 — "OPTIONS /user/login HTTP/1.1" 200 0
[2025-09-19 16:12:27,829] ERROR django.request:253 — Internal Server Error: /user/login
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/user/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
[2025-09-19 16:12:27,832] ERROR django.server:213 — "POST /user/login HTTP/1.1" 500 63387
[2025-09-19 16:12:39,814] ERROR django.request:253 — Internal Server Error: /user/login
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/user/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
[2025-09-19 16:12:39,817] ERROR django.server:213 — "POST /user/login HTTP/1.1" 500 63387
[2025-09-19 16:12:41,528] ERROR django.request:253 — Internal Server Error: /user/login
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/user/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
[2025-09-19 16:12:41,530] ERROR django.server:213 — "POST /user/login HTTP/1.1" 500 63387
[2025-09-19 16:12:47,016] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-19 16:12:47,039] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 19:32:22,274] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-19 19:32:23,668] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:32:23,738] INFO django.server:213 — "GET /media/catalog/487793279_I0LTg7r.png HTTP/1.1" 304 0
[2025-09-19 19:32:23,905] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:32:26,375] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-19 19:32:26,394] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 19:32:31,243] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:34:03,054] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:34:50,435] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:35:24,504] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:35:50,788] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:36:16,408] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:38:35,398] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:39:03,930] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:39:43,536] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:40:28,155] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:41:21,112] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:43:39,000] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:43:52,122] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:44:05,685] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:44:28,226] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:47:27,241] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:51:18,323] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:53:47,061] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:54:14,942] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:55:20,616] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:56:01,913] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:56:46,533] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:57:24,677] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:57:42,211] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:58:29,170] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:59:11,436] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 19:59:47,034] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:00:09,262] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:00:33,682] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:02:00,380] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:02:23,826] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:03:37,366] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-19 20:03:37,389] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 20:03:42,542] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:04:54,920] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:05:40,923] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:06:09,783] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:06:27,765] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:08:06,803] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:09:26,781] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:10:16,352] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:12:22,852] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-19 20:12:22,872] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:12:39,887] WARNING django.request:253 — Not Found: /
[2025-09-19 20:12:39,888] WARNING django.server:213 — "GET / HTTP/1.1" 404 2922
[2025-09-19 20:12:40,177] WARNING django.request:253 — Not Found: /favicon.ico
[2025-09-19 20:12:40,179] WARNING django.server:213 — "GET /favicon.ico HTTP/1.1" 404 2973
[2025-09-19 20:12:43,779] INFO django.server:213 — "GET /admin/ HTTP/1.1" 302 0
[2025-09-19 20:12:43,862] INFO django.server:213 — "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4173
[2025-09-19 20:12:47,176] INFO django.server:213 — "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2025-09-19 20:12:47,247] INFO django.server:213 — "GET /admin/ HTTP/1.1" 200 13218
[2025-09-19 20:12:50,973] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 37
[2025-09-19 20:12:50,981] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:13:07,663] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 20:13:18,698] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 20:13:18,701] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 37
[2025-09-19 20:13:22,097] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:13:27,086] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 37
[2025-09-19 20:13:27,092] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:13:29,617] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 20:13:31,320] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 20:13:31,324] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 37
[2025-09-19 20:13:40,726] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-19 20:13:43,780] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-19 20:13:45,737] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 06:43:31,015] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 06:45:18,725] INFO django.utils.autoreload:265 — /app/cart/models.py changed, reloading.
[2025-09-20 06:45:19,083] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 06:46:31,276] INFO django.utils.autoreload:265 — /app/cart/models.py changed, reloading.
[2025-09-20 06:46:31,639] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 06:47:36,722] INFO django.utils.autoreload:265 — /app/cart/models.py changed, reloading.
[2025-09-20 06:47:37,073] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 06:48:29,498] INFO django.utils.autoreload:265 — /app/cart/models.py changed, reloading.
[2025-09-20 06:48:29,901] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 06:49:04,395] WARNING django.request:253 — Not Found: /
[2025-09-20 06:49:04,396] WARNING django.server:213 — "GET / HTTP/1.1" 404 2922
[2025-09-20 06:49:04,484] WARNING django.request:253 — Not Found: /favicon.ico
[2025-09-20 06:49:04,485] WARNING django.server:213 — "GET /favicon.ico HTTP/1.1" 404 2973
[2025-09-20 06:49:15,944] WARNING django.request:253 — Not Found: /api/cart
[2025-09-20 06:49:15,944] WARNING django.server:213 — "GET /api/cart HTTP/1.1" 404 2964
[2025-09-20 06:49:39,424] WARNING django.request:253 — Not Found: /cart/api/cart
[2025-09-20 06:49:39,424] WARNING django.server:213 — "GET /cart/api/cart HTTP/1.1" 404 4411
[2025-09-20 06:49:57,247] INFO django.server:213 — "GET /cart HTTP/1.1" 301 0
[2025-09-20 06:49:57,295] ERROR django.request:253 — Internal Server Error: /cart/
[2025-09-20 06:49:57,296] ERROR django.server:213 — "GET /cart/ HTTP/1.1" 500 5246
[2025-09-20 06:49:57,315] INFO django.server:213 — "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3426
[2025-09-20 06:49:57,315] INFO django.server:213 — "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[2025-09-20 06:49:57,320] INFO django.server:213 — "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[2025-09-20 06:49:57,321] INFO django.server:213 — "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1793
[2025-09-20 06:49:57,323] INFO django.server:213 — "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
[2025-09-20 06:49:57,323] INFO django.server:213 — "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3796
[2025-09-20 06:49:57,325] INFO django.server:213 — "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[2025-09-20 06:49:57,326] INFO django.server:213 — "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[2025-09-20 06:49:57,327] INFO django.server:213 — "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[2025-09-20 06:49:57,329] INFO django.server:213 — "GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 200 59
[2025-09-20 06:49:57,329] INFO django.server:213 — "GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 200 87533
[2025-09-20 06:49:57,330] INFO django.server:213 — "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
[2025-09-20 06:52:35,134] INFO django.utils.autoreload:265 — /app/cart/models.py changed, reloading.
[2025-09-20 06:52:35,509] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 06:55:14,228] INFO django.utils.autoreload:265 — /app/cart/utils.py changed, reloading.
[2025-09-20 06:55:14,769] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 06:55:21,478] INFO django.utils.autoreload:265 — /app/cart/utils.py changed, reloading.
[2025-09-20 06:55:21,837] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 06:57:47,065] INFO django.utils.autoreload:265 — /app/cart/views.py changed, reloading.
[2025-09-20 06:57:47,430] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 06:57:56,663] WARNING django.request:253 — Not Found: /
[2025-09-20 06:57:56,664] WARNING django.server:213 — "GET / HTTP/1.1" 404 2922
[2025-09-20 06:58:01,703] ERROR django.request:253 — Internal Server Error: /cart/
[2025-09-20 06:58:01,704] ERROR django.server:213 — "GET /cart/ HTTP/1.1" 500 5388
[2025-09-20 06:58:17,378] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 06:58:45,108] WARNING django.request:253 — Not Found: /
[2025-09-20 06:58:45,109] WARNING django.server:213 — "GET / HTTP/1.1" 404 2922
[2025-09-20 06:58:49,829] INFO django.server:213 — "GET /cart/ HTTP/1.1" 200 5150
[2025-09-20 11:20:52,499] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 11:20:59,477] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 37
[2025-09-20 11:20:59,517] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 11:20:59,534] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 37
[2025-09-20 11:20:59,552] INFO django.server:213 — "GET /media/catalog/487793279_I0LTg7r.png HTTP/1.1" 304 0
[2025-09-20 11:20:59,576] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 11:21:01,675] INFO django.server:213 — "GET /admin/ HTTP/1.1" 200 13218
[2025-09-20 11:21:02,159] WARNING django.request:253 — Not Found: /favicon.ico
[2025-09-20 11:21:02,160] WARNING django.server:213 — "GET /favicon.ico HTTP/1.1" 404 2973
[2025-09-20 11:21:19,326] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-20 11:21:20,347] INFO django.server:213 — "OPTIONS /cart/api/add/1/ HTTP/1.1" 200 0
[2025-09-20 11:21:20,485] ERROR django.request:253 — Internal Server Error: /cart/api/add/1/
[2025-09-20 11:21:20,487] ERROR django.server:213 — "POST /cart/api/add/1/ HTTP/1.1" 500 268
[2025-09-20 11:21:46,271] ERROR django.request:253 — Internal Server Error: /admin/cart/cartitem/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column cart_cartitem.cart_id does not exist
LINE 1: SELECT "cart_cartitem"."id", "cart_cartitem"."cart_id", "car...
                                     ^
HINT:  Perhaps you meant to reference the column "cart_cartitem.cart_id_id".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2163, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column cart_cartitem.cart_id does not exist
LINE 1: SELECT "cart_cartitem"."id", "cart_cartitem"."cart_id", "car...
                                     ^
HINT:  Perhaps you meant to reference the column "cart_cartitem.cart_id_id".

[2025-09-20 11:21:46,280] ERROR django.server:213 — "GET /admin/cart/cartitem/ HTTP/1.1" 500 158820
[2025-09-20 11:21:50,559] INFO django.server:213 — "GET /admin/ HTTP/1.1" 200 13218
[2025-09-20 11:21:51,603] ERROR django.request:253 — Internal Server Error: /admin/cart/carts/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column cart_carts.user_id does not exist
LINE 1: SELECT "cart_carts"."id", "cart_carts"."user_id", "cart_cart...
                                  ^
HINT:  Perhaps you meant to reference the column "cart_carts.user_id_id".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2163, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column cart_carts.user_id does not exist
LINE 1: SELECT "cart_carts"."id", "cart_carts"."user_id", "cart_cart...
                                  ^
HINT:  Perhaps you meant to reference the column "cart_carts.user_id_id".

[2025-09-20 11:21:51,609] ERROR django.server:213 — "GET /admin/cart/carts/ HTTP/1.1" 500 157318
[2025-09-20 11:21:52,997] INFO django.server:213 — "GET /admin/ HTTP/1.1" 200 13218
[2025-09-20 11:21:54,806] INFO django.server:213 — "GET /admin/products/product/ HTTP/1.1" 200 17106
[2025-09-20 11:21:54,846] INFO django.server:213 — "GET /static/admin/css/base.css HTTP/1.1" 304 0
[2025-09-20 11:21:54,847] INFO django.server:213 — "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
[2025-09-20 11:21:54,859] INFO django.server:213 — "GET /static/admin/js/theme.js HTTP/1.1" 304 0
[2025-09-20 11:21:54,864] INFO django.server:213 — "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[2025-09-20 11:21:54,865] INFO django.server:213 — "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[2025-09-20 11:21:54,866] INFO django.server:213 — "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[2025-09-20 11:21:54,866] INFO django.server:213 — "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[2025-09-20 11:21:54,871] INFO django.server:213 — "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[2025-09-20 11:21:54,872] INFO django.server:213 — "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[2025-09-20 11:21:54,882] INFO django.server:213 — "GET /admin/jsi18n/ HTTP/1.1" 200 3342
[2025-09-20 11:21:54,885] INFO django.server:213 — "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[2025-09-20 11:21:54,897] INFO django.server:213 — "GET /static/admin/js/core.js HTTP/1.1" 304 0
[2025-09-20 11:21:54,904] INFO django.server:213 — "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[2025-09-20 11:21:54,909] INFO django.server:213 — "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[2025-09-20 11:21:54,912] INFO django.server:213 — "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[2025-09-20 11:21:54,959] INFO django.server:213 — "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[2025-09-20 11:21:54,964] INFO django.server:213 — "GET /static/admin/js/filters.js HTTP/1.1" 304 0
[2025-09-20 11:21:54,976] INFO django.server:213 — "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
[2025-09-20 11:21:54,978] INFO django.server:213 — "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
[2025-09-20 11:21:54,981] INFO django.server:213 — "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[2025-09-20 11:21:56,855] ERROR django.request:253 — Internal Server Error: /admin/cart/cartitem/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column cart_cartitem.cart_id does not exist
LINE 1: SELECT "cart_cartitem"."id", "cart_cartitem"."cart_id", "car...
                                     ^
HINT:  Perhaps you meant to reference the column "cart_cartitem.cart_id_id".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 246, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2163, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column cart_cartitem.cart_id does not exist
LINE 1: SELECT "cart_cartitem"."id", "cart_cartitem"."cart_id", "car...
                                     ^
HINT:  Perhaps you meant to reference the column "cart_cartitem.cart_id_id".

[2025-09-20 11:21:56,861] ERROR django.server:213 — "GET /admin/cart/cartitem/ HTTP/1.1" 500 158837
[2025-09-20 11:22:39,136] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-20 11:22:39,140] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 37
[2025-09-20 11:22:40,475] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:02:22,149] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 37
[2025-09-20 12:02:22,150] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:02:24,265] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-20 12:02:38,487] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:03:11,118] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 37
[2025-09-20 12:03:11,121] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:04:23,139] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 37
[2025-09-20 12:04:23,142] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:05:51,632] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:05:51,632] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 37
[2025-09-20 12:05:56,372] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-20 12:05:57,493] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:06:27,323] WARNING django.request:253 — Not Found: /users/logut
[2025-09-20 12:06:27,324] WARNING django.server:213 — "GET /users/logut HTTP/1.1" 404 2973
[2025-09-20 12:06:39,856] WARNING django.request:253 — Not Found: /users/logout
[2025-09-20 12:06:39,857] WARNING django.server:213 — "GET /users/logout HTTP/1.1" 404 2976
[2025-09-20 12:06:47,688] WARNING django.request:253 — Not Found: /users/logout
[2025-09-20 12:06:47,689] WARNING django.server:213 — "GET /users/logout HTTP/1.1" 404 2976
[2025-09-20 12:06:51,425] INFO django.server:213 — "GET /user/logout HTTP/1.1" 301 0
[2025-09-20 12:06:51,497] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 5227
[2025-09-20 12:06:55,699] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 5230
[2025-09-20 12:07:00,127] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:07:00,160] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:07:01,726] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:07:01,754] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:07:10,367] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-20 12:27:59,457] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:27:59,474] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-20 12:28:26,225] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:28:26,256] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:28:34,133] INFO django.server:213 — "GET /user/login/ HTTP/1.1" 200 6829
[2025-09-20 12:29:31,104] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 6914
[2025-09-20 12:30:11,488] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:31:50,061] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-20 12:31:51,542] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 12:32:02,762] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-20 12:32:03,584] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 12:37:21,686] ERROR django.request:253 — Internal Server Error: /user/login/
[2025-09-20 12:37:21,687] ERROR django.server:213 — "POST /user/login/ HTTP/1.1" 500 6975
[2025-09-20 12:37:57,036] ERROR django.request:253 — Internal Server Error: /user/login/
[2025-09-20 12:37:57,037] ERROR django.server:213 — "POST /user/login/ HTTP/1.1" 500 6975
[2025-09-20 12:38:01,013] INFO django.server:213 — "GET /user/login/ HTTP/1.1" 200 6829
[2025-09-20 12:38:07,810] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:38:08,790] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:38:11,796] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:38:13,304] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:38:14,039] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:38:20,775] ERROR django.request:253 — Internal Server Error: /user/login/
[2025-09-20 12:38:20,776] ERROR django.server:213 — "POST /user/login/ HTTP/1.1" 500 6975
[2025-09-20 12:38:26,040] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:38:28,548] ERROR django.request:253 — Internal Server Error: /user/login/
[2025-09-20 12:38:28,549] ERROR django.server:213 — "POST /user/login/ HTTP/1.1" 500 6966
[2025-09-20 12:38:32,430] ERROR django.request:253 — Internal Server Error: /user/login/
[2025-09-20 12:38:32,431] ERROR django.server:213 — "POST /user/login/ HTTP/1.1" 500 6975
[2025-09-20 12:38:35,263] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:39:22,539] INFO users.views:77 — user: 1
[2025-09-20 12:39:22,601] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 7065
[2025-09-20 12:39:32,243] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:39:33,291] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:39:34,450] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:39:39,602] INFO django.server:213 — "GET /user/login/ HTTP/1.1" 200 6829
[2025-09-20 12:39:43,778] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:39:49,443] INFO users.views:77 — user: 1
[2025-09-20 12:39:49,450] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 7065
[2025-09-20 12:39:54,161] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:39:54,810] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:39:58,614] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-20 12:40:51,899] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-20 12:40:53,211] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 12:42:17,886] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-20 12:42:19,138] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 12:42:44,501] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-20 12:42:45,426] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 12:43:28,880] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-20 12:43:30,138] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 12:44:18,961] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-20 12:44:19,748] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 12:44:32,442] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:44:39,598] ERROR django.request:253 — Internal Server Error: /user/login/
[2025-09-20 12:44:39,599] ERROR django.server:213 — "POST /user/login/ HTTP/1.1" 500 6944
[2025-09-20 12:44:43,140] INFO django.server:213 — "GET /user/login/ HTTP/1.1" 200 6829
[2025-09-20 12:44:45,263] ERROR django.request:253 — Internal Server Error: /user/login/
[2025-09-20 12:44:45,264] ERROR django.server:213 — "POST /user/login/ HTTP/1.1" 500 6944
[2025-09-20 12:45:18,834] INFO django.utils.autoreload:265 — /app/users/views.py changed, reloading.
[2025-09-20 12:45:20,145] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 12:45:21,769] INFO django.server:213 — "GET /user/login/ HTTP/1.1" 200 6829
[2025-09-20 12:45:34,753] INFO users.views:77 — user: 1
[2025-09-20 12:45:34,823] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 7132
[2025-09-20 12:45:45,979] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5294
[2025-09-20 12:45:51,034] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5294
[2025-09-20 12:46:09,507] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 5227
[2025-09-20 12:46:12,132] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 5230
[2025-09-20 12:46:15,577] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:46:17,941] INFO django.server:213 — "GET /user/login/ HTTP/1.1" 200 6829
[2025-09-20 12:46:26,273] INFO users.views:77 — user: 1
[2025-09-20 12:46:26,282] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 7132
[2025-09-20 12:46:29,476] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5294
[2025-09-20 12:46:35,098] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 37
[2025-09-20 12:46:35,107] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-20 12:46:35,796] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:46:38,307] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-20 12:46:39,743] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:46:41,263] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-20 12:46:49,078] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 5227
[2025-09-20 12:46:51,962] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 5230
[2025-09-20 12:46:54,842] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:46:57,148] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:47:01,756] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:47:01,789] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:47:50,996] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:47:51,052] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:48:03,722] INFO django.server:213 — "OPTIONS /user/login HTTP/1.1" 200 0
[2025-09-20 12:48:03,768] ERROR django.request:253 — Internal Server Error: /user/login
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/user/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
[2025-09-20 12:48:03,771] ERROR django.server:213 — "POST /user/login HTTP/1.1" 500 63387
[2025-09-20 12:48:07,388] ERROR django.request:253 — Internal Server Error: /user/login
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/user/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
[2025-09-20 12:48:07,390] ERROR django.server:213 — "POST /user/login HTTP/1.1" 500 63387
[2025-09-20 12:48:11,772] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:48:11,802] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:48:20,766] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:48:20,784] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-20 12:48:42,648] ERROR django.request:253 — Internal Server Error: /user/login
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/user/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
[2025-09-20 12:48:42,650] ERROR django.server:213 — "POST /user/login HTTP/1.1" 500 63387
[2025-09-20 12:48:59,463] ERROR django.request:253 — Internal Server Error: /user/login
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/user/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
[2025-09-20 12:48:59,466] ERROR django.server:213 — "POST /user/login HTTP/1.1" 500 63387
[2025-09-20 12:49:00,376] ERROR django.request:253 — Internal Server Error: /user/login
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/user/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
[2025-09-20 12:49:00,379] ERROR django.server:213 — "POST /user/login HTTP/1.1" 500 63387
[2025-09-20 12:49:00,807] ERROR django.request:253 — Internal Server Error: /user/login
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/user/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
[2025-09-20 12:49:00,809] ERROR django.server:213 — "POST /user/login HTTP/1.1" 500 63387
[2025-09-20 12:50:36,542] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:50:36,603] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:50:47,037] INFO django.server:213 — "OPTIONS /user/login/ HTTP/1.1" 200 0
[2025-09-20 12:50:47,759] INFO users.views:77 — user: 1
[2025-09-20 12:50:47,765] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 136
[2025-09-20 12:51:07,308] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:51:07,344] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:51:17,112] INFO users.views:77 — user: 1
[2025-09-20 12:51:17,117] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 136
[2025-09-20 12:51:27,435] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:51:28,416] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:51:31,093] INFO users.views:77 — user: 1
[2025-09-20 12:51:31,098] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 136
[2025-09-20 12:51:31,315] INFO users.views:77 — user: 1
[2025-09-20 12:51:31,319] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 136
[2025-09-20 12:51:31,506] INFO users.views:77 — user: 1
[2025-09-20 12:51:31,511] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 136
[2025-09-20 12:51:31,670] INFO users.views:77 — user: 1
[2025-09-20 12:51:31,676] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 136
[2025-09-20 12:51:47,358] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:51:47,374] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-20 12:53:08,709] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:53:09,408] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:53:12,828] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:53:12,852] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:55:57,301] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:55:57,319] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-20 12:55:57,384] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:55:57,409] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:56:06,380] INFO django.server:213 — "OPTIONS /user/login/ HTTP/1.1" 200 0
[2025-09-20 12:56:06,826] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:56:06,849] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:56:07,275] INFO users.views:77 — user: 1
[2025-09-20 12:56:07,281] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 136
[2025-09-20 12:56:17,535] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:56:18,602] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
[2025-09-20 12:57:01,377] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:57:01,402] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:57:14,402] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:57:14,427] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:57:14,886] INFO users.views:77 — user: 1
[2025-09-20 12:57:14,890] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 136
[2025-09-20 12:57:39,224] ERROR django.request:253 — Internal Server Error: /user/login/
[2025-09-20 12:57:39,226] ERROR django.server:213 — "POST /user/login/ HTTP/1.1" 500 105
[2025-09-20 12:57:39,608] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 12:57:39,667] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:59:32,663] INFO users.views:77 — user: 1
[2025-09-20 12:59:32,674] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 7132
[2025-09-20 12:59:35,450] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5294
[2025-09-20 12:59:38,175] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 37
[2025-09-20 12:59:38,178] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:59:43,231] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-20 12:59:45,316] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 12:59:48,134] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-20 12:59:48,826] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 13:00:08,075] INFO django.server:213 — "GET /products/1/ HTTP/1.1" 200 803
[2025-09-20 13:00:08,081] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 37
[2025-09-20 13:00:17,144] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 5227
[2025-09-20 13:00:21,791] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 13:00:21,817] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 13:00:30,756] ERROR django.request:253 — Internal Server Error: /user/login/
[2025-09-20 13:00:30,759] ERROR django.server:213 — "POST /user/login/ HTTP/1.1" 500 105
[2025-09-20 13:00:31,112] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 13:00:31,134] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 13:00:41,657] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 6914
[2025-09-20 13:02:10,809] ERROR django.request:253 — Internal Server Error: /user/login/
[2025-09-20 13:02:10,811] ERROR django.server:213 — "POST /user/login/ HTTP/1.1" 500 105
[2025-09-20 13:02:11,179] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 13:02:11,206] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 13:02:37,163] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 23
[2025-09-20 13:02:37,188] INFO django.server:213 — "GET /products/api/ HTTP/1.1" 200 982
[2025-09-20 13:02:43,616] ERROR django.request:253 — Internal Server Error: /user/login/
[2025-09-20 13:02:43,618] ERROR django.server:213 — "POST /user/login/ HTTP/1.1" 500 105
[2025-09-20 13:02:54,996] INFO django.server:213 — "GET /user/login/ HTTP/1.1" 200 6829
[2025-09-20 13:08:19,614] INFO django.utils.autoreload:265 — /app/users/serializers.py changed, reloading.
[2025-09-20 13:08:20,891] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 13:08:38,228] ERROR django.request:253 — Internal Server Error: /user/login/
[2025-09-20 13:08:38,229] ERROR django.server:213 — "POST /user/login/ HTTP/1.1" 500 105
[2025-09-20 13:09:19,459] ERROR django.request:253 — Internal Server Error: /user/login/
[2025-09-20 13:09:19,461] ERROR django.server:213 — "POST /user/login/ HTTP/1.1" 500 6966
[2025-09-20 13:09:25,090] INFO django.utils.autoreload:265 — /app/users/serializers.py changed, reloading.
[2025-09-20 13:09:26,318] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-20 13:09:28,020] INFO django.server:213 — "GET /user/login/ HTTP/1.1" 200 6829
[2025-09-20 13:09:31,931] INFO users.views:77 — user: 1
[2025-09-20 13:09:32,000] INFO django.server:213 — "POST /user/login/ HTTP/1.1" 200 7132
[2025-09-20 13:09:37,626] INFO django.server:213 — "GET /user/login/ HTTP/1.1" 200 6859
[2025-09-20 13:09:46,838] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5294
[2025-09-20 13:09:50,830] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 5227
[2025-09-20 13:09:51,760] INFO django.server:213 — "GET /user/logout/ HTTP/1.1" 200 5230
[2025-09-20 13:09:53,658] INFO django.server:213 — "GET /user/api/check-auth/ HTTP/1.1" 200 5224
>>>>>>> 0a37971ef570aeb7a173d19fe84909b2c133b0a5
[2025-09-21 16:04:11,676] INFO django.utils.autoreload:667 — Watching for file changes with StatReloader
[2025-09-21 16:04:19,133] WARNING django.request:253 — Not Found: /
[2025-09-21 16:04:19,135] WARNING django.server:213 — "GET / HTTP/1.1" 404 2922
